spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
#    url: jdbc:mariadb://218.239.207.244:30303/sb_react_todo
    url: jdbc:mariadb://218.239.207.244:30303/sb_react_todo
    username: minjun
    password: alswns123!
    driver-class-name: org.mariadb.jdbc.Driver


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.d0uwhs.sbreacttodoserver.domain
  mapper-locations: mybatis/**.xml


logging:
  level:
    root: info
